workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy

jobs:
  build:
    docker:
      - image: cimg/node:16.8.0

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: yarn build

  build-deploy:
    machine: true
    steps:
      - checkout

      - run:
        name: Deploy Application
        command: |
          set -x
          sudo curl https://cli-assets.heroku.com/install.sh | sh
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:login
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:push -a pihorb-chat-app web
          HEROKU_API_KEY=${HEROKU_API_KEY} heroku container:release -a pihorb-chat-app web
