# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

jobs:
  install_deps:
    docker:
      - image: circleci/node@4.1
    steps:
      - checkout
      - run:
        name: Install deps
        command: |
          yarn install
